services:
  prod:
    build:
      context: ./
      target: prod
    image: cobyamar/portfolio:1.0.0
    ports: 
      - 4200:4200
  dev:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true 
    build:
      context: ./
      target: dev
    ports: 
      - 4200:4200
      - 49153:49153
    volumes:
      - ./:/app
      - /app/node_modules/