services:
  dev:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true 
    build:
      context: ./
      target: dev
    ports: 
      - 4200:4200
      - 49153:49153 # for webpack-dev-server
    volumes:
      - ./:/app
      - /app/node_modules/